POST http://localhost:8080/consumer/api/v1/messages
Content-Type: application/json

{
  "id": 1,
  "description": "order 1",
  "date": "2021-03-18",
  "client": {
    "clientId": 1,
    "name": "Jhon"
  }
}

<> 2022-03-18T131721.500.json
<> 2022-03-18T125927.500.json
<> 2022-03-18T125902.400.json
